spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://c-c9qlodb67vpo12m5rgb3.rw.mdb.yandexcloud.net:6432/climbooking_prod
    username: climbooking_prod
    password: d22-QqU-pqJ-fFd
  liquibase:
    change-log: changelog/changelog.xml

server:
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
